// Auth
export const REGISTER_PENDING = 'REGISTER_PENDING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_PENDING = 'LOGOUT_PENDING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
export const REFRESH_TOKEN_PENDING = 'REFRESH_TOKEN_PENDING'
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_FAIL = 'REFRESH_TOKEN_FAIL'

// Messages
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const RECEIVE_MESSAGES = 'RECEIVE_MESSAGES'
export const DECODE_MESSAGES = 'DECODE_MESSAGES'

// Screens
export const VIEW_MESSAGE = 'VIEW_MESSAGE'
export const VIEW_LIST_MESSAGES = 'VIEW_LIST_MESSAGES'
export const VIEW_SEND_MESSAGE = 'VIEW_SEND_MESSAGE'
